import { Inter } from "next/font/google";
import "@src/styles/globals.css";
import Nav from "@src/components/Nav";
import Provider from "@src/components/Provider";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Craftopia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <div className="main">
            <div className="gradient" />
          </div>
          <main className="app">
            <Nav />
            <Suspense>
              {children}
            </Suspense>
          </main>
        </Provider>
      </body>
    </html>
  );
}
